DOMAIN = "heiseonline"

FEEDS = {
    'https://www.heise.de/rss/heise-atom.xml': 'heise online News',
    'https://www.heise.de/rss/heise-Rubrik-IT-atom.xml': 'heise online IT',
    'https://www.heise.de/rss/heise-Rubrik-Wissen-atom.xml': 'heise online Wissen',
    'https://www.heise.de/rss/heise-Rubrik-Mobiles-atom.xml': 'heise online Mobiles',
    'https://www.heise.de/rss/heise-Rubrik-Entertainment-atom.xml': 'heise online Entertainment',
    'https://www.heise.de/rss/heise-Rubrik-Netzpolitik-atom.xml': 'heise online Netzpolitik',
    'https://www.heise.de/rss/heise-Rubrik-Wirtschaft-atom.xml': 'heise online Wirtschaft',
    'https://www.heise.de/rss/heise-Rubrik-Journal-atom.xml': 'heise online Journal',
    'https://www.heise.de/rss/heise-top-atom.xml': 'heise online Top-News',
    'https://www.heise.de/netze/netzwerk-tools/imonitor-internet-stoerungen/feed/aktuelle-meldungen/': 'Netzwerk-Tools – iMonitor – Internet-Störungen',
    'https://www.heise.de/rss/heiseplus-atom.xml': 'Alle Inhalte von heise+',
    'https://www.heise.de/autos/feed.xml': 'heise Autos',
    'https://www.heise.de/developer/rss/news-atom.xml': 'heise Developer',
    'https://www.heise.de/developer/rss/dotnet-doktor-blog-atom.xml': 'Der Dotnet-Doktor',
    'https://www.heise.de/developer/rss/next-big-thing-blog-atom.xml': 'the next big thing',
    'https://www.heise.de/developer/rss/tales-from-the-web-side-blog-atom.xml': 'Tales from the Web side',
    'https://www.heise.de/developer/rss/continuous-architecture-blog-atom.xml': 'Continuous Architecture',
    'https://www.heise.de/developer/rss/der-pragmatische-architekt-blog-atom.xml': 'Der Pragmatische Architekt',
    'https://www.heise.de/developer/rss/modernes-cplusplus-blog-atom.xml': 'Modernes C++',
    'https://www.heise.de/developer/rss/colspan-dev-blog-atom.xml': 'colspan',
    'https://www.heise.de/developer/rss/ich-roll-dann-mal-aus-atom.xml': '"Ich roll' dann mal aus"',
    'https://www.heise.de/developer/rss/well-organized-blog-atom.xml': 'Well Organized',
    'https://www.heise.de/developer/rss/neuigkeiten-von-der-insel-blog-atom.xml': 'Neuigkeiten von der Insel',
    'https://www.heise.de/developer/rss/von-menschen-und-maschinen-blog-atom.xml': 'Von Menschen und Maschinen',
    'https://www.heise.de/foto/rss/news-atom.xml': 'heise Foto',
    'https://www.heise.de/download/feed/top': 'Top-Programme bei heise Download',
    'https://www.heise.de/security/rss/news-atom.xml': 'heise Security',
    'https://www.heise.de/security/rss/alert-news-atom.xml': 'Security-Alert Meldungen',
    'https://www.heise.de/ct/feed.xml': "Aktuelle Artikel der c't",
    'https://www.heise.de/make/rss/hardware-hacks-atom.xml': 'Make - Neueste Meldungen',
    'https://www.heise.de/ix/feed.xml': 'iX Magazin',
    'https://www.heise.de/mac-and-i/feed.xml': 'Mac & i',
    'https://www.heise.de/tp/news-atom.xml': 'Telepolis',
    'https://www.techstage.de/rss.xml': 'TechStage'
}
